export enum PermissionName {
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  VIEW_PRODUCTS = 'VIEW_PRODUCTS',
  PLACE_ORDER = 'PLACE_ORDER',
  VIEW_ORDERS = 'VIEW_ORDERS',
  ACCESS_DASHBOARD = 'ACCESS_DASHBOARD',
}
