
import { SiteHeader } from "@/components/site-header";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RoleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SiteHeader value="Dashboard &gt; Snapshots" />
      <div className="flex flex-1 flex-col">
        <div className="@container/main flex flex-1 flex-col gap-2">
          <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
            <div className="flex justify-between items-center px-4 lg:px-6">
              {/* <div>
                <h2 className="text-2xl font-semibold">Snapshots</h2>
              </div> */}
            </div>
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
