[wokwi]
version = 1
firmware = 'build/flasher_args.json'   # đường dẫn tới firmware bạn đã build (ESP-IDF)
elf = 'build/example_app.elf'          # file elf để debug (nếu có)

# Kích hoạt port forwarding (ví dụ)
rfc2217ServerPort = 4000

[[net.forward]]
from = "localhost:8180"
to = "target:80"
