// src/permissions/permissions.enum.ts

export enum PermissionName {
  VIEW_USERS = 'VIEW_USERS',
  MANAGE_USERS = 'MANAGE_USERS',

  VIEW_ROLES = 'VIEW_ROLES',
  MANAGE_ROLES = 'MANAGE_ROLES',

  MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',
  VIEW_PRODUCTS = 'VIEW_PRODUCTS',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  VIEW_ORDERS = 'VIEW_ORDERS',
  PLACE_ORDER = 'PLACE_ORDER',

  ACCESS_DASHBOARD = 'ACCESS_DASHBOARD',

  VIEW_MEDIA = 'VIEW_MEDIA',
  MANAGE_MEDIA = 'MANAGE_MEDIA',

  VIEW_MAIL = 'VIEW_MAIL',
  MANAGE_MAIL = 'MANAGE_MAIL',

  VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS',
  MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS',

  VIEW_PERMISSIONS = 'VIEW_PERMISSIONS',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  VIEW_STATS = 'VIEW_STATS',
}
