import type { Metadata } from "next";
import "../share/globals.css";
import Tanstack from "@adapter/share/provider/tanstack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className="antialiased">
        <Tanstack>{children}</Tanstack>
      </body>
    </html>
  );
}
