import type { Metadata } from "next";
import { loadDictionaryOnce } from "../lang";
import Link from "next/link";
import Image from "next/image";
import { TopBarProducts } from "@/components/products-route/topBar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  const languages = ["en", "vi"];
  return languages.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "de" }>;
}>) {
  const { lang } = await params;
  loadDictionaryOnce(lang);
  return (
    <div>
      {children}
    </div>
  );
}
