import type { Metadata } from "next";
import { loadDictionaryOnce } from "../lang";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  const languages = ["en", "vi"];
  return languages.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "de" }>;
}>) {
  const { lang } = await params;
  loadDictionaryOnce(lang);
  return <div>{children}</div>;
}
