import type { Metadata } from "next";
import { loadDictionaryOnce } from "../lang";
import Tanstack from "@adapter/share/provider/tanstack";
import { useAuthGuard } from "@adapter/share/hooks/useAuthGuard";
import { LoginForm } from "@/app/[lang]/(auth)/login/components/LoginForm";
import LoginPage from "./(auth)/login/page";
import { api } from "@adapter/share/api/apiClient";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  const languages = ["en", "vi"];
  return languages.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "de" }>;
}>) {
  const { lang } = await params;
  loadDictionaryOnce(lang);
  const isAuth = api.hasToken();
  return <Tanstack>{isAuth ? children : <LoginPage />}</Tanstack>;
}
