import { SiteHeader } from "@/components/site-header";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <SiteHeader value="Dashboard &gt; Cấu hình thiết bị" />
      <div className="flex flex-1 flex-col">
        <div className="@container/main flex flex-1 flex-col gap-2">
          <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
            <div className="flex justify-between items-center px-4 lg:px-6">
              <div>
                <h1 className="text-2xl font-semibold">Cấu hình thiết bị</h1>
              </div>
            </div>
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
